USE Hitas4;
GO

DECLARE @Check_Date as Date;
DECLARE @Date AS VARCHAR(10)
DECLARE @Month AS VARCHAR(2);
DECLARE @Year AS VARCHAR(4);
SET @Month = CAST(MONTH(SYSDATETIME()) AS VARCHAR(2))
SET @YEAR = CAST(YEAR(SYSDATETIME()) AS VARCHAR(4))
SET @Check_Date = CAST(@Month + '/01/' + @year AS DATE);

SELECT	HASHBYTES('SHA2_256', M.MWR_EMAIL) AS EHash,
		IIF(ISNULL(U.UNT_NAAM,'') ='','Onbekend', U.UNT_NAAM) AS Unit,
		HASHBYTES('SHA2_256', M.MWR_EMAIL+ IIF(ISNULL(U.UNT_NAAM,'') ='','Onbekend', U.UNT_NAAM)) AS hash_row
  FROM [dbo].[vw_HIS_MEDEWERKER] AS M
  LEFT JOIN [dbo].[HIS_UNIT] AS U ON U.UNT_ID = M.UNT_CODE
  WHERE (MWR_INDIENST <= @Check_Date AND MWR_UITDIENST > @Check_Date) 
		AND MWR_INTERN='I';
